apply plugin: 'com.android.application'

android {
    namespace 'jp.co.cyberagent.android.gpuimage.sample'
    compileSdk 35

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 35
        applicationId 'jp.co.cyberagent.android.gpuimage.sample'
        versionCode 1
        versionName '1.0'
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
        }

        // instrumentTest.setRoot('tests')  // Deprecated
    }

    lintOptions {
        abortOnError true
    }
}
repositories {
    google()
    mavenCentral()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}

dependencies {
    implementation project(':library')
//    implementation 'jp.co.cyberagent.android.gpuimage:gpuimage-library:+@aar'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
}